[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[build]
installCommand = "pip install -r requirements.txt"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[environments]
python = { version = "3.11" }